### ISSUE TITLE
Looped video giving error

### ISSUE THREAD

**Issue by DreamView** [KenT2/pipresents-kms#2] opened 2023-09-24 12:59 UTC
When I loop a video in a show I get the following error±
  File "/home/pi/pipresents/pp_mpvdriver.py", line 197, in show_status_loop
    if self.user_pause is False and self.player.time_remaining<0.4:
TypeError: '<' not supported between instances of 'NoneType' and 'float'

I´ll take a look if I can resolve the myself, seem a little bug, but it brakes the show

**Comment by KenT2** [comment] 2023-09-24 18:40
I suspect the problem is that the video track has ended when the test was done so mpv reports None rather than an integer.
Try decreasing the loop delay time in line 205, as low as 10 mS should be OK for CPU usage
If that fails try increasing the 0.4 (secs) and see if that sorts it.

**Comment by DreamView** [comment] 2023-09-25 08:23
Hi Ken, thanks for your quick response, I decreased the loop time to 50 and increased the detection level to 0.5 I'll keep you informed.

**Comment by DreamView** [comment] 2023-09-25 09:51
Still breaking every now and then (video finished when looping). I changed the "< 0.5" to "is None" and now it is stable but no freezed frame at the end. This is no problem for this project so a good solution for now.

**Comment by KenT2** [comment] 2023-10-10 10:55
Fixed in Version 1.5.3c. In addition to improving the 'near end of video detection' I have made it forgiving of the occasional overrun.

**Closed by KenT2** 2023-10-10 10:55 UTC
